[package]
name = "aoc2025-nostd"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"

[profile.profiling]
inherits = "release"
debug = "full"

[dependencies]
libc = { version = "0.2", default-features = false }

[lints.clippy]
missing_safety_doc = "allow"
manual_is_multiple_of = "allow"
print_with_newline = "allow"